### ISSUE TITLE
日時表示が0埋めされない

### ISSUE THREAD

**Issue by h3d63h06** [taka868/BoshuKAN#1]
20:04 と表示されることが望ましい

<img width="800" alt="20220606201005" src="https://user-images.githubusercontent.com/40066313/172150538-47c08d0f-c7ff-4233-81c5-a32d868c7c68.png">

**Comment by taka868** [comment]
f4823b9d3df5479a8e5be24075a5f85b7f1ec708
ゼロパディングするようにしました。
