### ISSUE TITLE
参加表明しても参加者一覧に追加されない

### ISSUE THREAD

**Issue by h3d63h06** [taka868/BoshuKAN#2]
<img width="500" alt="20220606201715" src="https://user-images.githubusercontent.com/40066313/172150921-69da4c50-be80-4708-a26f-06f2ace29a49.png">

**Comment by taka868** [comment]
参加ボタン時の参加者一覧取得メソッドに引数を入れ忘れて例外になっていました
e6be487e559cb0a426a133ecf5d6b9e9913b137e
